#!/bin/bash

APP_ROOT=$(dirname "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")")
APP_NAME="cryptomator"

service_start() {
    echo "$APP_NAME started"
}

service_stop() {
    echo "$APP_NAME stopped"
}

service_status() {
    echo "running"
}

case "$1" in
    start)
        service_start
        exit 0
        ;;
    stop)
        service_stop
        exit 0
        ;;
    restart)
        service_stop
        sleep 1
        service_start
        exit 0
        ;;
    status)
        service_status
        exit 0
        ;;
    *)
        echo "Usage: $(basename $0) {start|stop|status|restart}"
        exit 1
        ;;
esac
